import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios'
import { useState } from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState()
  const [location, setLocation] = useState()
  const [weather, setWeather] = useState('')
  const [errorMessage, setErrorMessage] = useState('')

  let apiKey = 'c3dc1fd95482bf1d21216ce93d579fa9'
  let lang = 'en'
  let units = 'metric'
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${location}&units=${units}&appid=${apiKey}&lang=${lang}`

  const searchLocation = (event) => {
    if (event.key === 'Enter') {
      axios.get(url)
        .then((response) => {
          console.clear()
          console.log(response)
          console.log(weather)
          console.log(data)
          setData(response.data)
          setWeather(response.data.weather)
          setErrorMessage('')
        }).catch(err => {
          console.log(err)
          setErrorMessage('Please enter another location.')
          setData()
          setWeather('')
        })
      setLocation('')
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {errorMessage}
        <div className={styles.header}>
          <input
            value={location}
            onChange={event => setLocation(event.target.value)}
            placeholder='Enter location'
            onKeyDown={searchLocation}
            type='text'
          />
          {data ? <p className={styles.name}>{data.name}</p> : <></>}
          {weather && weather.map((w, i) => {
            return (
              <div key={i}>
                <p className={styles.desc}>{w.description}</p>
              </div>
            )
          })}
        </div>
        <div className={styles.stats}>
          <div>
            <h3>Temperature</h3>
            {data ? <p><span className={styles.stat}>{data.main.temp}</span>℃</p> : <></>}
          </div>
          <div>
            <h3>Feels like</h3>
            {data ? <p><span className={styles.stat}>{data.main.feels_like}</span>℃</p> : <></>}
          </div>
          <div>
            <h3>Wind speed</h3>
            {data ? <p><span className={styles.stat}>{data.wind.speed}</span>m/s</p> : <></>}
          </div>
        </div>
      </main>
    </>
  )
}
